version: "3.9"

services:
  backend:
    volumes:
      - .:/code
    environment:
      - ENV=development
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  celery:
    volumes:
      - .:/code
    environment:
      - ENV=development
    command: >
      sh -c "watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A app.tasks worker --loglevel=info"
